/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as ConsoleIndexRouteImport } from './routes/console.index'
import { Route as PortalTaxasRouteImport } from './routes/portal.taxas'
import { Route as PortalPropostaRouteImport } from './routes/portal.proposta'
import { Route as PortalPagamentoRouteImport } from './routes/portal.pagamento'
import { Route as PortalLoginRouteImport } from './routes/portal.login'
import { Route as PortalDs160RouteImport } from './routes/portal.ds160'
import { Route as PortalDocumentosRouteImport } from './routes/portal.documentos'
import { Route as PortalContratoRouteImport } from './routes/portal.contrato'
import { Route as ConsoleLoginRouteImport } from './routes/console.login'
import { Route as ConsoleAuditoriaRouteImport } from './routes/console.auditoria'
import { Route as ConsoleOrcamentoNovoRouteImport } from './routes/console.orcamento.novo'
import { Route as ConsoleClienteIdRouteImport } from './routes/console.cliente.$id'
import { Route as ConsoleOrcamentoIdEditarRouteImport } from './routes/console.orcamento.$id.editar'

const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRoute,
} as any)
const PortalTaxasRoute = PortalTaxasRouteImport.update({
  id: '/taxas',
  path: '/taxas',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPropostaRoute = PortalPropostaRouteImport.update({
  id: '/proposta',
  path: '/proposta',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPagamentoRoute = PortalPagamentoRouteImport.update({
  id: '/pagamento',
  path: '/pagamento',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDs160Route = PortalDs160RouteImport.update({
  id: '/ds160',
  path: '/ds160',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDocumentosRoute = PortalDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => PortalRoute,
} as any)
const PortalContratoRoute = PortalContratoRouteImport.update({
  id: '/contrato',
  path: '/contrato',
  getParentRoute: () => PortalRoute,
} as any)
const ConsoleLoginRoute = ConsoleLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleAuditoriaRoute = ConsoleAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleOrcamentoNovoRoute = ConsoleOrcamentoNovoRouteImport.update({
  id: '/orcamento/novo',
  path: '/orcamento/novo',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleClienteIdRoute = ConsoleClienteIdRouteImport.update({
  id: '/cliente/$id',
  path: '/cliente/$id',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleOrcamentoIdEditarRoute =
  ConsoleOrcamentoIdEditarRouteImport.update({
    id: '/orcamento/$id/editar',
    path: '/orcamento/$id/editar',
    getParentRoute: () => ConsoleRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/console/auditoria': typeof ConsoleAuditoriaRoute
  '/console/login': typeof ConsoleLoginRoute
  '/portal/contrato': typeof PortalContratoRoute
  '/portal/documentos': typeof PortalDocumentosRoute
  '/portal/ds160': typeof PortalDs160Route
  '/portal/login': typeof PortalLoginRoute
  '/portal/pagamento': typeof PortalPagamentoRoute
  '/portal/proposta': typeof PortalPropostaRoute
  '/portal/taxas': typeof PortalTaxasRoute
  '/console/': typeof ConsoleIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/console/cliente/$id': typeof ConsoleClienteIdRoute
  '/console/orcamento/novo': typeof ConsoleOrcamentoNovoRoute
  '/console/orcamento/$id/editar': typeof ConsoleOrcamentoIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/console/auditoria': typeof ConsoleAuditoriaRoute
  '/console/login': typeof ConsoleLoginRoute
  '/portal/contrato': typeof PortalContratoRoute
  '/portal/documentos': typeof PortalDocumentosRoute
  '/portal/ds160': typeof PortalDs160Route
  '/portal/login': typeof PortalLoginRoute
  '/portal/pagamento': typeof PortalPagamentoRoute
  '/portal/proposta': typeof PortalPropostaRoute
  '/portal/taxas': typeof PortalTaxasRoute
  '/console': typeof ConsoleIndexRoute
  '/portal': typeof PortalIndexRoute
  '/console/cliente/$id': typeof ConsoleClienteIdRoute
  '/console/orcamento/novo': typeof ConsoleOrcamentoNovoRoute
  '/console/orcamento/$id/editar': typeof ConsoleOrcamentoIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/console': typeof ConsoleRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/console/auditoria': typeof ConsoleAuditoriaRoute
  '/console/login': typeof ConsoleLoginRoute
  '/portal/contrato': typeof PortalContratoRoute
  '/portal/documentos': typeof PortalDocumentosRoute
  '/portal/ds160': typeof PortalDs160Route
  '/portal/login': typeof PortalLoginRoute
  '/portal/pagamento': typeof PortalPagamentoRoute
  '/portal/proposta': typeof PortalPropostaRoute
  '/portal/taxas': typeof PortalTaxasRoute
  '/console/': typeof ConsoleIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/console/cliente/$id': typeof ConsoleClienteIdRoute
  '/console/orcamento/novo': typeof ConsoleOrcamentoNovoRoute
  '/console/orcamento/$id/editar': typeof ConsoleOrcamentoIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/console'
    | '/portal'
    | '/console/auditoria'
    | '/console/login'
    | '/portal/contrato'
    | '/portal/documentos'
    | '/portal/ds160'
    | '/portal/login'
    | '/portal/pagamento'
    | '/portal/proposta'
    | '/portal/taxas'
    | '/console/'
    | '/portal/'
    | '/console/cliente/$id'
    | '/console/orcamento/novo'
    | '/console/orcamento/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/console/auditoria'
    | '/console/login'
    | '/portal/contrato'
    | '/portal/documentos'
    | '/portal/ds160'
    | '/portal/login'
    | '/portal/pagamento'
    | '/portal/proposta'
    | '/portal/taxas'
    | '/console'
    | '/portal'
    | '/console/cliente/$id'
    | '/console/orcamento/novo'
    | '/console/orcamento/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/console'
    | '/portal'
    | '/console/auditoria'
    | '/console/login'
    | '/portal/contrato'
    | '/portal/documentos'
    | '/portal/ds160'
    | '/portal/login'
    | '/portal/pagamento'
    | '/portal/proposta'
    | '/portal/taxas'
    | '/console/'
    | '/portal/'
    | '/console/cliente/$id'
    | '/console/orcamento/novo'
    | '/console/orcamento/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsoleRoute: typeof ConsoleRouteWithChildren
  PortalRoute: typeof PortalRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/console/': {
      id: '/console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/portal/taxas': {
      id: '/portal/taxas'
      path: '/taxas'
      fullPath: '/portal/taxas'
      preLoaderRoute: typeof PortalTaxasRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/proposta': {
      id: '/portal/proposta'
      path: '/proposta'
      fullPath: '/portal/proposta'
      preLoaderRoute: typeof PortalPropostaRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/pagamento': {
      id: '/portal/pagamento'
      path: '/pagamento'
      fullPath: '/portal/pagamento'
      preLoaderRoute: typeof PortalPagamentoRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/login': {
      id: '/portal/login'
      path: '/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/ds160': {
      id: '/portal/ds160'
      path: '/ds160'
      fullPath: '/portal/ds160'
      preLoaderRoute: typeof PortalDs160RouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/documentos': {
      id: '/portal/documentos'
      path: '/documentos'
      fullPath: '/portal/documentos'
      preLoaderRoute: typeof PortalDocumentosRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/contrato': {
      id: '/portal/contrato'
      path: '/contrato'
      fullPath: '/portal/contrato'
      preLoaderRoute: typeof PortalContratoRouteImport
      parentRoute: typeof PortalRoute
    }
    '/console/login': {
      id: '/console/login'
      path: '/login'
      fullPath: '/console/login'
      preLoaderRoute: typeof ConsoleLoginRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/auditoria': {
      id: '/console/auditoria'
      path: '/auditoria'
      fullPath: '/console/auditoria'
      preLoaderRoute: typeof ConsoleAuditoriaRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/orcamento/novo': {
      id: '/console/orcamento/novo'
      path: '/orcamento/novo'
      fullPath: '/console/orcamento/novo'
      preLoaderRoute: typeof ConsoleOrcamentoNovoRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/cliente/$id': {
      id: '/console/cliente/$id'
      path: '/cliente/$id'
      fullPath: '/console/cliente/$id'
      preLoaderRoute: typeof ConsoleClienteIdRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/orcamento/$id/editar': {
      id: '/console/orcamento/$id/editar'
      path: '/orcamento/$id/editar'
      fullPath: '/console/orcamento/$id/editar'
      preLoaderRoute: typeof ConsoleOrcamentoIdEditarRouteImport
      parentRoute: typeof ConsoleRoute
    }
  }
}

interface ConsoleRouteChildren {
  ConsoleAuditoriaRoute: typeof ConsoleAuditoriaRoute
  ConsoleLoginRoute: typeof ConsoleLoginRoute
  ConsoleIndexRoute: typeof ConsoleIndexRoute
  ConsoleClienteIdRoute: typeof ConsoleClienteIdRoute
  ConsoleOrcamentoNovoRoute: typeof ConsoleOrcamentoNovoRoute
  ConsoleOrcamentoIdEditarRoute: typeof ConsoleOrcamentoIdEditarRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleAuditoriaRoute: ConsoleAuditoriaRoute,
  ConsoleLoginRoute: ConsoleLoginRoute,
  ConsoleIndexRoute: ConsoleIndexRoute,
  ConsoleClienteIdRoute: ConsoleClienteIdRoute,
  ConsoleOrcamentoNovoRoute: ConsoleOrcamentoNovoRoute,
  ConsoleOrcamentoIdEditarRoute: ConsoleOrcamentoIdEditarRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

interface PortalRouteChildren {
  PortalContratoRoute: typeof PortalContratoRoute
  PortalDocumentosRoute: typeof PortalDocumentosRoute
  PortalDs160Route: typeof PortalDs160Route
  PortalLoginRoute: typeof PortalLoginRoute
  PortalPagamentoRoute: typeof PortalPagamentoRoute
  PortalPropostaRoute: typeof PortalPropostaRoute
  PortalTaxasRoute: typeof PortalTaxasRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalContratoRoute: PortalContratoRoute,
  PortalDocumentosRoute: PortalDocumentosRoute,
  PortalDs160Route: PortalDs160Route,
  PortalLoginRoute: PortalLoginRoute,
  PortalPagamentoRoute: PortalPagamentoRoute,
  PortalPropostaRoute: PortalPropostaRoute,
  PortalTaxasRoute: PortalTaxasRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsoleRoute: ConsoleRouteWithChildren,
  PortalRoute: PortalRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
